<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta http-equiv="X-UA-Compatible" content="ie=edge">';
echo '';
echo '<!-- Google Font -->';
echo '<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900|Roboto:300,400,700" rel="stylesheet">';
echo '';
echo '<!-- Bootstrap CSS -->';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"';
echo 'integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />';
echo '';
echo '<!-- Font Awesome -->';
echo '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"';
echo 'integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous" />';
echo '';
echo '<!-- Custom styles for this template -->';
echo '<link href="assets/css/app.css" rel="stylesheet" />';
echo '<title>Keerthana Jayakumar | Portfolio</title>';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<!-- No defined header section -->';
echo '';
echo '<!-- Main content goes here split into sections/fragments -->';
echo '<main>';
echo '';
echo '<!-- Utilizes flexbox styling not taught in class -->';
echo '<section id="trunk-vanta">';
echo '<section class="fragment fragment-one">';
echo '<div class="headers">';
echo '<h1> keetu. </h1>';
echo '<h3> data scientist | data engineer | software developer</h3>';
echo '</div>';
echo '';
echo '<div class="learn">';
echo '';
echo '<!-- You could hyperlink this down with a smooth scroll -->';
echo '<a href="#Click_to_learn_more" style = "color: rgb(194, 194, 194)">';
echo '<p><strong>learn more</strong></p>';
echo '<i class="fas fa-chevron-down" style = "color: rgb(194, 194, 194)"></i>';
echo '</a>';
echo '</div>';
echo '</section>';
echo '</section>';
echo '<section class="fragment fragment-two">';
echo '<a id="Click_to_learn_more">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-md-12">';
echo '';
echo '<!-- Edit this text with a brief intoduction / brand statement etc. -->';
echo '<h4>';
echo 'Keerthana (Keetu) is a Mechatronics Engineer and Data Analyst with strong math and statistics skills.';
echo 'She has a background in Python, SQL, VBA, Javascript and Machine Learning from the University of Toronto's Data Analytics Bootcamp.';
echo '';
echo '</h5>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '';
echo '<div class="learn">';
echo '<!-- You could hyperlink this down with a smooth scroll -->';
echo '<a href="#Click_for_projects" style = "color: rgb(21, 85, 50)">';
echo '<p>click for projects </p>';
echo '<i class="fas fa-chevron-down"></i>';
echo '</a>';
echo '</div>';
echo '';
echo '</section>';
echo '<section class="fragment fragment-two-point-five">';
echo '<a id="featured_project">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-md-5">';
echo '';
echo '<!-- Edit this text with a brief intoduction / brand statement etc. -->';
echo '<h3>';
echo 'FEATURED PROJECT';
echo '</h3>';
echo '<h4>';
echo 'Deciphering the Indus script using Natural Language Processing, Machine Learning, ETL and Statistical Analysis';
echo '</h4>';
echo '<a class="btn btn-primary" href = " https://deciphering-indus-script.herokuapp.com/" role = "button">Click for website</a>';
echo '<a class="btn btn-primary" href = " https://github.com/Kee2u/Deciphering_the_Indus_Valley_Script" role = "button">Click for Github</a>';
echo '</div>';
echo '<div class="col-md-7">';
echo '<img src="assets/images/Unicorn3.jpg" class="img-fluid" alt="Responsive image">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '';
echo '</section>';
echo '<section class="fragment fragment-three">';
echo '<a id="Click_for_projects">';
echo '<h3>Things I've Made</h3>';
echo '<hr class="title-underline">';
echo '<div class="container carousel-container">';
echo '';
echo '<!-- begin carousel -->';
echo '<!-- you should replace the placeholder images with actual images from your projects -->';
echo '<!-- images should be 800*600 or a matching ratio for best results -->';
echo '<div id="portfolioCarousel" class="carousel slide" data-ride="carousel">';
echo '<ol class="carousel-indicators">';
echo '<li data-target="#portfolioCarousel" data-slide-to="0" class="active custom-indicator">';
echo '</li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="1" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="2" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="3" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="4" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="5" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="6" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="7" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="8" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="9" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="10" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="11" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="12" class="custom-indicator"></li>';
echo '<li data-target="#portfolioCarousel" data-slide-to="13" class="custom-indicator"></li>';
echo '';
echo '</ol>';
echo '<div class="carousel-inner">';
echo '<div class="carousel-item active">';
echo '';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/earth.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Mapping Earthquakes</h4>';
echo '<p>Created an interactive map using javascript, leaflet, D3 library and Mapbox.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Mapping_Earthquakes" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/plotly.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Plotly Diversity</h4>';
echo '<p>Used Javascript, plotly, html and bootstrap to create a dynamic web visualization dashboard.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Election_Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/mars1.jpg" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Mission to Mars</h4>';
echo '<p>Collected information on Mars from four websites using web scraping tools. Used chrome developer tools to read HTML, Beautiful Soup and Splinter to automate the scrape, Mongo to store the data and Flask to display the scraped content.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Mission-to-Mars" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/top-cryptocurrencies.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Cryptocurrencies</h4>';
echo '<p>Using unsupervised methods namely Sklearn's standardization functions, PCA and K means algorithm to create a cryptocurrency investment portfolio.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Cryptocurrencies" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/tableau.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Bikesharing</h4>';
echo '<p>Using Tableau to create visualizations of New York ridesharing data.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/bikesharing" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/WM.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>World Weather Analysis</h4>';
echo '<p>Created an app using Google maps and Open Weather Map APIS. Can be used to recommend hotels based on traveller's weather preferences.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/World_Weather_Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/Surfs_up1.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Surfs Up</h4>';
echo '<p>Used Pandas and SQLite to study temperature and precipitation data in Oahu. Results from data analysis used to decide if opening a Surf Shop in the location is feasible.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Surfs_Up" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/Movies_ETL1.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Movies ETL</h4>';
echo '<p>Scraped movie data from Wikipedia, Kaggle and MovieLens. Created a data pipeline to clean the data using ETL and Pandas with Jupyter Notebooks. Uploaded the cleaned data to SQL tables for further analysis.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Movies-ETL" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/DB1.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Employee Database</h4>';
echo '<p>Used PostgreSQL and PGAdmin4 to determine the impact of retiring employees on a fictional company.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Pewlett-Hackard-Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/s1.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>School District Analysis</h4>';
echo '<p>Used python on Jupyter notebooks to analyze test scores.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/School_District_Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/pol1.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Election Analysis</h4>';
echo '<p>Used Python to assist a Colorado board of elections by calculating election poll results and county with highest voter turnout.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Election_Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/R.PNG" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Mechacar Statistical Analysis</h4>';
echo '<p>Statistical Analysis of car manufacturing data using R. Tests include t-tests, ANOVA, and regression analysis.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/MechaCar_Statistical_Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/Vine-header.jpg" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Amazon Vine Analysis</h4>';
echo '<p>Using Pyspark, AWS RDS and PGAdmin to analyze amazon reviews.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Amazon_Vine_Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '<!--image here -->';
echo '<img src="assets/images/network.png" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Neural Network Charity Analysis</h4>';
echo '<p>Creating neural networks with Scikit-Learn, Tensorflow and Keras to determine if organizations that received funding, used their resources effectively.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Neural_Network_Charity_Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '<!--image here -->';
echo '<img src="assets/images/ta.jpg" class="img-fluid" alt="Responsive image">';
echo '<div class="carousel-caption d-none d-md-block">';
echo '<h4>Credit Risk Analysis</h4>';
echo '<p>Predicting credit risk using logisitic regression machine learning model.</p>';
echo '<a class="btn btn-primary" href = "https://github.com/Kee2u/Credit_Risk_Analysis" role = "button">View Code</a>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-item">';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</a>';
echo '';
echo '</section>';
echo '<section class="fragment fragment-four">';
echo '';
echo '<h3>Technology I Use</h3>';
echo '<hr class="title-underline">';
echo '<div class="container">';
echo '<div class="labels">';
echo '<div class="tech">Python</div>';
echo '<div class="tech">R</div>';
echo '<div class="tech">SQL</div>';
echo '<div class="tech">JavaScript</div>';
echo '<div class="tech">HTML/CSS</div>';
echo '<div class="tech">Tableau</div>';
echo '<div class="tech">Big Data</div>';
echo '<div class="tech">Machine Learning</div>';
echo '<div class="tech">MATLAB</div>';
echo '<div class="tech">C / C++</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</section>';
echo '<section class="fragment fragment-five">';
echo '<h3>My Education</h3>';
echo '<hr class="title-underline">';
echo '';
echo '<!-- Don't forget to swap out the universities and education to match your own-->';
echo '<div class="container">';
echo '<h5> University of Toronto</h5>';
echo '<p class="credential"> Data Analytics Bootcamp | 2021</p>';
echo '<h5> University of Toronto</h5>';
echo '<p class="credential"> B.A. Applied Science and Engineering | 2013 - 2018</p>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '</main>';
echo '';
echo '<footer>';
echo '<section class="fragment fragment-six">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col">';
echo '<h6>keerthana jayakumar</h6>';
echo '';
echo '<!--update these links to match your own social media profiles -->';
echo '<a href="https://www.instagram.com/artbykeetu/" class="social-icon"><i class="fab fa-instagram"></i></a>';
echo '<a href="https://www.linkedin.com/in/keerthanajayakumar/" class="social-icon"><i class="fab fa-linkedin"></i></a>';
echo '<a href="https://github.com/Kee2u" class="social-icon"><i class="fab fa-github"></i></a>';
echo '<a href="mailto:<keetu.jk@gmail.com>" class="social-icon"><i class="fas fa-envelope"></i></a>';
echo '<p class="text-muted copyright">Keerthana Jayakumar &copy; 2021 - 2022 </p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '</footer>';
echo '';
echo '<!-- Bootstrap core JavaScript -->';
echo '<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"';
echo 'integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"';
echo 'crossorigin="anonymous"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"';
echo 'integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"';
echo 'crossorigin="anonymous"></script>';
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"';
echo 'integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"';
echo 'crossorigin="anonymous"></script>';
echo '';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.net.min.js"></script>';
echo '<script src="assets/js/vanta.js"></script>';
echo '';
echo '';
echo '</body>';
echo '';
echo '</html>';
?>